version: '3.8'

services:
  db:
    image: postgres:13.4-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    container_name: poultry
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/opt/code/staticfiles
      - static_volume:/opt/code/mediafiles
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/opt/code/staticfiles
      - static_volume:/opt/code/mediafiles
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  db_data:
  static_volume:
  mediafiles:
