version: '3.8'

services:
  db:
    image: postgres:13.4-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    container_name: poultry
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/opt/code
    depends_on:
      - db

volumes:
  db_data:
