# Generated by Django 4.1.4 on 2023-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_farmexpense_expense_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="opening",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="recieving",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
