# Generated by Django 4.1.4 on 2023-03-30 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_otherexpense_otherincome_rename_expense_farmexpense_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flock",
            name="sale_date",
        ),
    ]
