# Generated by Django 4.1.4 on 2023-03-30 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_flock_sale_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flock",
            name="sale_quantity",
        ),
    ]
