# Generated by Django 4.1.4 on 2023-05-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_medicine_description_medicine_moved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="flock",
        ),
        migrations.AddField(
            model_name="medicine",
            name="farm",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.farm"
            ),
            preserve_default=False,
        ),
    ]
