# Generated by Django 4.1.4 on 2023-05-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_medicine_flock_medicine_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='usage',
        ),
        migrations.CreateModel(
            name='MedicineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comapny')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_medicines', to='app.flock')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='app.medicine')),
            ],
        ),
    ]
