# Generated by Django 4.1.4 on 2023-09-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_feed_cr_alter_medicine_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='flock',
        ),
        migrations.AddField(
            model_name='feed',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.farm'),
            preserve_default=False,
        ),
    ]
