# Generated by Django 4.1.4 on 2023-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_remove_feed_flock_feed_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="moved",
            field=models.IntegerField(default=0),
        ),
    ]
