name: deploy-to-prod
on:
  push:
    branches:
      - main

jobs:
  pre-commit_and_test:
    uses: ./.github/workflows/ci.yml
  deploy:
    concurrency:
      group: ${{ github.ref }}
    needs: pre-commit_and_test
    name: "Deploy to prod"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}

      - name: Pull the latest code to the prod environment
        run: ssh prod 'cd poultry && git pull origin'

      - name: Start containers
        run: |
          ssh prod 'cd poultry && bash scripts/start_server.sh'

      - name: Test the App
        run: |
          ssh prod 'if [ $( docker ps -a | grep poultry | wc -l ) -gt 0 ]; then  echo "poultry exists"; else   echo "poultry does not exist" && raise error; fi'
