name: deploy-to-prod
on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - name: Install Node Dependencies
        run: npm ci
      - name: Build Front-end
        run: |
          npm run build
      - uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Check missing migrations
        run: python manage.py makemigrations --check --dry-run
      - name: Run Tests
        env:
          SECRET_KEY: fake_key
          DEBUG: True
        run: |
          python manage.py test
  deploy:
    concurrency:
      group: ${{ github.ref }}
    name: "Deploy to prod"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}

      - name: Pull the latest code to the prod environment
        run: ssh prod 'cd poultry && git pull origin'

      - name: Start containers
        run: |
          ssh prod 'cd poultry && bash scripts/start_server.sh'

      - name: Test the App
        run: |
          ssh prod 'if [ $( docker ps -a | grep poultry | wc -l ) -gt 0 ]; then  echo "poultry exists"; else   echo "poultry does not exist" && raise error; fi'
